import importlib.util
import os

import bpy

from .utils import (
    append_log,
    apply_transforms,
    ensure_absolute_dir,
    sanitize_resource_name,
    safe_mkdir,
    safe_write_json,
    safe_write_text,
    set_active_object,
    show_message_box,
)


def _sollumz_available():
    return importlib.util.find_spec("sollumz") is not None or hasattr(bpy.ops, "sollumz")


def _select_objects(objects):
    bpy.ops.object.select_all(action='DESELECT')
    for obj in objects:
        obj.select_set(True)
    if objects:
        bpy.context.view_layer.objects.active = objects[0]


def _call_export(op_name, filepath):
    operator = getattr(bpy.ops.sollumz, op_name, None)
    if operator is None:
        return False
    operator(filepath=filepath)
    return True


def export_fivem_resource(context, settings, shell_obj, collision_obj, export_rooms):
    if not _sollumz_available():
        show_message_box(
            "Sollumz add-on not found.\n\nInstall steps:\n"
            "1) Download Sollumz from https://github.com/Sollumz/Sollumz\n"
            "2) Install via Blender Preferences > Add-ons > Install\n"
            "3) Enable the Sollumz add-on\n",
            title="Sollumz Missing",
            icon='ERROR',
        )
        append_log(context, "Export aborted: Sollumz is missing.")
        return False

    resource_name = sanitize_resource_name(settings.resource_name)
    output_dir = ensure_absolute_dir(settings.output_folder)
    if not output_dir:
        append_log(context, "No output folder provided. Export aborted.")
        return False

    resource_dir = os.path.join(output_dir, resource_name)
    stream_dir = os.path.join(resource_dir, "stream")
    meta_dir = os.path.join(resource_dir, "meta")
    preview_dir = os.path.join(resource_dir, "preview")

    safe_mkdir(stream_dir)
    safe_mkdir(meta_dir)
    safe_mkdir(preview_dir)

    fxmanifest = """fx_version 'cerulean'
    game 'gta5'
    this_is_a_map 'yes'
    files {
      'stream/*.ydr',
      'stream/*.ybn',
      'stream/*.ytyp'
    }
    """

    safe_write_text(os.path.join(resource_dir, "fxmanifest.lua"), fxmanifest)

    readme = (
        f"{resource_name} - Generated by DE Scripts MLO Studio\n\n"
        "Drop this resource into your FiveM resources folder and add it to server.cfg.\n"
    )
    safe_write_text(os.path.join(resource_dir, "README.md"), readme)

    build_spec = {
        "resource_name": resource_name,
        "prompt": settings.prompt_text,
        "preset": settings.building_preset,
        "detail_level": settings.detail_level,
        "floors": settings.cached_floors,
        "bays": settings.cached_bays,
        "rooms": settings.cached_rooms,
        "export_furnishings": settings.export_furnishings_as_meshes,
    }
    safe_write_json(os.path.join(meta_dir, "build_spec.json"), build_spec)

    if shell_obj is None:
        append_log(context, "Shell mesh not found. Export aborted.")
        return False

    apply_transforms(shell_obj)
    export_targets = [shell_obj]

    if settings.export_furnishings_as_meshes:
        for obj in bpy.data.objects:
            if obj.name.startswith("de_furn_"):
                export_targets.append(obj)

    if export_rooms:
        for obj in bpy.data.objects:
            if obj.name.startswith("room_") or obj.name.startswith("portal_"):
                export_targets.append(obj)

    _select_objects(export_targets)
    ydr_path = os.path.join(stream_dir, f"{resource_name}.ydr")
    ydr_ok = _call_export("export_ydr", ydr_path)
    if ydr_ok:
        append_log(context, f"Exported YDR: {ydr_path}")
    else:
        append_log(context, "Sollumz export_ydr operator not found.")

    ybn_ok = False
    if collision_obj:
        apply_transforms(collision_obj)
        _select_objects([collision_obj])
        ybn_path = os.path.join(stream_dir, f"{resource_name}.ybn")
        ybn_ok = _call_export("export_ybn", ybn_path)
        if ybn_ok:
            append_log(context, f"Exported YBN: {ybn_path}")
        else:
            append_log(context, "Sollumz export_ybn operator not found.")
    else:
        append_log(context, "Collision proxy missing; skipping YBN export.")

    _select_objects(export_targets)
    ytyp_path = os.path.join(stream_dir, f"{resource_name}.ytyp")
    ytyp_ok = _call_export("export_ytyp", ytyp_path)
    if ytyp_ok:
        append_log(context, f"Exported YTYP: {ytyp_path}")
    else:
        append_log(context, "Sollumz export_ytyp operator not found; skipping YTYP.")

    if not ydr_ok:
        append_log(context, "Warning: YDR export failed.")
    if collision_obj and not ybn_ok:
        append_log(context, "Warning: YBN export failed.")

    append_log(context, f"FiveM resource exported to {resource_dir}")
    return True
